// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1DeGn6vLbXvfN3d_PLDDGcr58BE0EmdA',
    appId: '1:775648584814:web:5e3687576be48131e8f27f',
    messagingSenderId: '775648584814',
    projectId: 'reusemart-e2733',
    authDomain: 'reusemart-e2733.firebaseapp.com',
    storageBucket: 'reusemart-e2733.firebasestorage.app',
    measurementId: 'G-MNHGR6V6SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4uD12znuOOr23sklIedvlAObR-Czz_Dc',
    appId: '1:775648584814:android:c021d64ac700b946e8f27f',
    messagingSenderId: '775648584814',
    projectId: 'reusemart-e2733',
    storageBucket: 'reusemart-e2733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAZTJlOUX7vEkFK5w6DTofhTuJvJUPsvc',
    appId: '1:775648584814:ios:2987e56b81f945aae8f27f',
    messagingSenderId: '775648584814',
    projectId: 'reusemart-e2733',
    storageBucket: 'reusemart-e2733.firebasestorage.app',
    iosBundleId: 'com.example.p3lMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAZTJlOUX7vEkFK5w6DTofhTuJvJUPsvc',
    appId: '1:775648584814:ios:2987e56b81f945aae8f27f',
    messagingSenderId: '775648584814',
    projectId: 'reusemart-e2733',
    storageBucket: 'reusemart-e2733.firebasestorage.app',
    iosBundleId: 'com.example.p3lMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1DeGn6vLbXvfN3d_PLDDGcr58BE0EmdA',
    appId: '1:775648584814:web:fa2167cc420e327fe8f27f',
    messagingSenderId: '775648584814',
    projectId: 'reusemart-e2733',
    authDomain: 'reusemart-e2733.firebaseapp.com',
    storageBucket: 'reusemart-e2733.firebasestorage.app',
    measurementId: 'G-4PG41HP231',
  );

}